[build]
    command = "pnpm run build:todo-list"
    publish = "dist/apps/todo-list/"

[build.environment]
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    CYPRESS_SUPPORT_FILE = "apps/todo-list-e2e/src/support/e2e.ts"
    CYPRESS_SCREENSHOTS_FOLDER = "dist/cypress/app/todo-list-e2e/screenshots"
    CYPRESS_VIDEOS_FOLDER = "dist/cypress/app/todo-list-e2e/videos"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
    package = "netlify-plugin-cypress"
    [plugins.inputs]
        record = true
        configFile = "apps/todo-list-e2e/cypress.config.ts"
